version: "3.2"

services:
  dev:
    container_name: contact-tracing-node
    image: parity/rust-builder:latest
    working_dir: /var/www/contact-tracing-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/contact-tracing-node/.cargo
    volumes:
      - .:/var/www/contact-tracing-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/contact-tracing-node --dev --ws-external"